In [1]:
import cv2

In [2]:
x=cv2.VideoCapture(0)

In [3]:
ret , ph= x.read()

In [4]:
ret

True

In [5]:
ph

array([[[154, 123, 138],
        [154, 125, 141],
        [151, 124, 140],
        ...,
        [147, 130, 167],
        [145, 132, 164],
        [143, 130, 162]],

       [[156, 125, 140],
        [156, 124, 141],
        [151, 124, 140],
        ...,
        [148, 131, 168],
        [148, 135, 167],
        [148, 135, 167]],

       [[156, 124, 141],
        [154, 125, 141],
        [150, 122, 141],
        ...,
        [147, 130, 167],
        [146, 133, 165],
        [148, 135, 167]],

       ...,

       [[191, 170, 162],
        [185, 164, 156],
        [180, 161, 154],
        ...,
        [ 78,  39,  24],
        [ 86,  46,  27],
        [ 94,  54,  35]],

       [[181, 162, 155],
        [177, 158, 151],
        [175, 157, 150],
        ...,
        [ 83,  44,  30],
        [ 94,  53,  38],
        [105,  62,  47]],

       [[168, 149, 144],
        [171, 152, 147],
        [173, 157, 151],
        ...,
        [ 85,  47,  35],
        [ 99,  57,  44],
        [108,  64,  51]]

In [6]:
cv2.imwrite("jup.png",ph)

True

In [7]:
x.release()

In [11]:
cv2.imshow("hi",ph)
cv2.waitKey()
cv2.destroyAllWindows()

 type(ph)

In [9]:
type(ph)

numpy.ndarray

In [21]:
ph[10]

array([[  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       ...,
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0]], dtype=uint8)

In [22]:
ph[10][0]

array([  0, 255,   0], dtype=uint8)

In [10]:
ph[10:51]=[0,255,0]

CROPPING IMAGE

In [19]:
new_photo=ph[30:700,10:800]


In [20]:
cv2.imshow("New photo",new_photo)
cv2.waitKey()
cv2.destroyAllWindows()